---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: testing
    api_version: v1
    kind: Namespace
    state: present

- name: Create MongoDB app
  kubernetes.core.k8s:
    state: present
    namespace: testing
    definition: "{{ lookup('file', 'files/mongoDB/{{ item }}.yaml') | from_yaml_all }}"
  loop:
    - 01-mongodb-cm
    - 02-mongodb-secret
    - 03-mongodb-sts
    - 04-mongodb-svc
  register: mongo_resources

- name: Create MongoDB Express deployment
  kubernetes.core.k8s:
    state: present
    namespace: testing
    definition: "{{ lookup('file', 'files/mongo-express.yaml') | from_yaml_all }}"

- name: Rollout MongoDB Express restart if configmap/secrets changed
  shell: kubectl rollout restart deployment mongo-express
  when: mongo_resources.changed