name: Ansible Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: lab01 
          cluster-name: lab-cluster

      - name: Install deps
        run: |
          sudo su
          source /opt/pipx/venvs/ansible-core/bin/activate
          sudo pip install kubernetes

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: kubernetes-deployment.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, encrypted vault password
          vault_password: ${{secrets.VAULT_PASS}}

